Repository corca-ai/adcio-ios-sdk, pull requests merged in 2023-11, with the labels that each got.

#5 Feature/implement agent webview
  Package.swift
  Sources/AdcioAgent/AdcioAgent.swift
Labels: feature request

#2 Feature/analytics add feature functions
  Package.swift
  Sources/AdcioAnalytics/AdcioAnalytics.swift
  Sources/AdcioAnalytics/Errors/AdcioNetworkError.swift
  Sources/AdcioAnalytics/Errors/JsonError.swift
  Sources/AdcioAnalytics/Model/AdcioLogOption.swift
  Sources/AdcioAnalytics/Network/API/EventAPI.swift
  Sources/AdcioAnalytics/Network/API/PerformanceAPI.swift
  Sources/AdcioAnalytics/Network/APIManager.swift
Labels: feature request

#6 Feature/placement add features
  Package.swift
  Sources/AdcioPlacement/AdcioPlacement.swift
  Sources/AdcioPlacement/Errors/AdcioNetworkError.swift
  Sources/AdcioPlacement/Errors/JsonError.swift
  Sources/AdcioPlacement/Model/AdcioSuggestion.swift
  Sources/AdcioPlacement/Model/AdcioSuggestionRawData.swift
  Sources/AdcioPlacement/Model/Banner.swift
  Sources/AdcioPlacement/Model/Gender.swift
  Sources/AdcioPlacement/Model/LogOptions.swift
  Sources/AdcioPlacement/Model/Product.swift
  Sources/AdcioPlacement/Network/APIManager.swift
  Sources/AdcioPlacement/Network/SuggestionAPI.swift
Labels: feature request

#7 ADCIO-1620) feat: receive agent web message
  Sources/AdcioAgent/AdcioAgent.swift
  Sources/AdcioAgent/AdcioCoordinator.swift
Labels: feature request

#8 ADCIO-1718) feat: update analytics scheme
  Sources/AdcioAnalytics/AdcioAnalytics.swift
  Sources/AdcioAnalytics/Model/AdcioLogOption.swift
  Sources/AdcioAnalytics/Network/API/PerformanceAPI.swift
Labels: bug, feature request

#9 ADCIO-1718) fix: remove non logoption entity value
  Sources/AdcioAnalytics/Model/AdcioLogOption.swift
Labels: bug
